name: tauri-build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Install Rust
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      # Step 3: Install Node.js (if your Tauri app requires it)
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.18.1

      # Step 4: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 5: Build the Tauri app
      - name: tauri-build
        uses: JonasKruckenberg/tauri-build@v9.2.0
        with:
          # Specify the binary to use for building (leave blank for default)
          runner: ""
          # Additional arguments for the build command
          args: ""
          # Root of the project (default is current working directory)
          projectPath: "."
          # Path to a custom Tauri configuration file
          configPath: "./src-tauri/tauri.conf.json"
          # Specify the target triple (e.g., x86_64-unknown-linux-gnu)
          target: ""
          # Set to true for debug builds
          debug: false
